name: jsaction
on:
  push:
jobs:
  test-js-action:
    name: job to test our JS action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: jsAction
        with:
          number1: 4
          number2: 2
      - run: echo ${{ steps.jsAction.outputs.result }}